### ISSUE TITLE
Like System on the comment vue

### ISSUE THREAD

**Issue by lb308** [jcc/blog#36] opened 2017-03-21 00:29 UTC
Hello to you I wanna thank you for your blog its awesome.
I wanna add the Like system to the comment and to the articles

so I add this the the template section in the Comment.vue
`<a href="javascript:;" @click="like(index)"><i class="ion-ios-heart"></i></a>`

I have this in the Javascritp section in Comment.vue
`            like(index) {
                this.comments[index].like = !this.comments[index].like
                this.comments[index].like ? this.comments[index].like_num++ : this.comments[index].like_num--
            }`

the question how can I make it works? do I have to add a field in the database comment table : like_num?

thanks for the help.

**Comment by jcc** [comment] 2017-03-21 01:27
You should code a new api for it. And then call it in Comment.vue. Thanks for your support. This is not a bug in the project.I closed this issue.

**Closed by jcc** 2017-03-21 01:27 UTC

**Comment by lb308** [comment] 2017-03-21 02:00
thanks a lot I will try it soon
